### ISSUE TITLE
Creating custom adapter

### ISSUE THREAD

**Issue by rpander93** [powersync-ja/powersync-web-sdk#20]
Hi,

I'm working on an app using Tauri and was looking into the possibility of creating a custom adapter that uses the [tauri sql plugin](https://github.com/tauri-apps/tauri-plugin-sql).

Curious to know from the dev team if this makes sense to do? Based on the blog article [here](https://www.powersync.com/blog/sqlite-persistence-on-the-web) it seems like the current web SDK is a bit sub-optimal due to platform constraints. My thinking was that by using SQLite directly, some of the overhead can be skipped.

Does this make sense? If yes, I might have a crack at it

**Comment by rkistner** [comment]
Using native APIs to access SQLite should be better both in terms of performance and predictable storage format, and something like tauri plugin sql that you mentioned should work well.

There is some functionality currently missing in the plugin that we'll need:
1. Support for transactions. Concurrent read transactions with WAL mode is a big bonus (helps for apps syncing large volumes of data).
2. Support for loading SQLite extensions, since the core of PowerSync is implemented as a [SQLite extension](https://github.com/powersync-ja/powersync-sqlite-core).

From a quick look, it seems like the underlying sqlx library does support the above, but it's not exposed via the tauri plugin yet.

**Comment by rpander93** [comment]
Okay - clear. When I get a change I'll try and get it working as a little project
